### ISSUE TITLE
 ./build/libcorrelation.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by YujiaoShi** [jgorgenucsd/corr_tf#4]
After "cmake .." and "make", when I run "python correlation_tests.py ", it reports error:

Traceback (most recent call last):
  File "correlation_tests.py", line 11, in <module>
    import correlation_layer as cl
  File "/home/yujiao/code/crossview_localisation/crop/corr_tf/correlation_layer.py", line 2, in <module>
    correlation_module = tf.load_op_library("./build/libcorrelation.so")
  File "/home/yujiao/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./build/libcorrelation.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

May I ask what I can do in this case?

**Comment by xjtuwh** [comment]
I meet the same problem. Can you tell me how to solve it?

**Comment by JunJuner** [comment]
I also meet the same problem. I solve the problem by this way. May by you can try.
According to https://tensorflow.google.cn/guide/extend/op?hl=en#gpu_support
I run
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
nvcc -std=c++11 -c -o correlation.cu.o correlation_gpu.cc.cu \
  ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

g++ -std=c++11 -shared -o libcorrelation.so correlation.cc \
  correlation.cu.o ${TF_CFLAGS[@]} -fPIC -lcudart ${TF_LFLAGS[@]}

nvcc -std=c++11 -c -o correlation_grad.cu.o correlation_grad_gpu.cc.cu \
  ${TF_CFLAGS[@]} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

g++ -std=c++11 -shared -o libcorrelation_grad.so correlation_grad.cc \
  correlation_grad.cu.o ${TF_CFLAGS[@]} -fPIC -lcudart -L ./ -lcorrelation ${TF_LFLAGS[@]}

After those, I get two files libcorrelation.so and libcorrelation_grad.so. I put both of them on the "build" directory and I can pass through the test.
